server:
  port: 9001
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user  #服务的名称"唯一"
  registry:
    address: zookeeper://192.168.92.128:2181?backup=192.168.92.128:2182,192.168.92.128:2183